# -*- coding: utf-8 -*-
"""可视化编排: 团关系图 / PL 画像墙 / 关系网 md / 杰克档案 / 编年史。

安全原则(重要):
    手写文档(杰克档案.md / 跑团宇宙编年史.md 等)是珍贵资产, **绝不无条件覆盖**。
    - 目标文件不存在, 或首行带 AUTO-GENERATED 标记 -> 直接生成;
    - 否则 -> 把自动生成的内容写到 <work>/reports/ 下的「更新建议」文件, 并明确告警,
      由主人决定是否合并。
"""
from __future__ import annotations

import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from trpg_agent import log
from trpg_agent.config import Config
from trpg_agent.data_utils import char_groups, collect_groups
from trpg_agent.visualize import net_html, pl_html
from trpg_agent.workspace import Workspace

AUTO_MARK = "<!-- AUTO-GENERATED by trpg-agent"


def _write_doc(target: Path, content: str, what: str, ws: Workspace) -> dict[str, Any]:
    if target.is_file():
        head = target.read_text(encoding="utf-8", errors="replace")[:200]
        if AUTO_MARK not in head:
            sug = ws.reports / f"{target.stem}_自动更新建议.md"
            sug.parent.mkdir(parents=True, exist_ok=True)
            sug.write_text(f"{AUTO_MARK} -->\n{content}", encoding="utf-8")
            log.warn(
                f"{what} 是人工维护的文档, 已把自动生成内容写到建议文件(不覆盖): {ws.rel(sug)}"
            )
            return {"path": ws.rel(target), "updated": False, "suggestion": ws.rel(sug)}
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content if AUTO_MARK in content else f"{AUTO_MARK} -->\n{content}", encoding="utf-8")
    log.ok(f"{what} 已生成: {ws.rel(target)}")
    return {"path": ws.rel(target), "updated": True}


def _esc(s: Any) -> str:
    return html.escape(str(s))


def relations_md(ws: Workspace, group: str) -> str:
    chars_doc = json.loads(ws.data_file("characters").read_text(encoding="utf-8"))
    rels_doc = json.loads(ws.data_file("relations").read_text(encoding="utf-8"))
    chars = [c for c in chars_doc.get("characters", []) if group in (c.get("groups") or [])]
    ids = {c["id"] for c in chars}
    rels = [r for r in rels_doc.get("relations", []) if r.get("from") in ids and r.get("to") in ids]
    by_id = {c["id"]: c for c in chars}

    # ⚠️ 标记必须在**首行**：`_write_doc()` 只看文件开头 200 字来决定「是不是自动生成物」。
    #    2026-10-05 前这里只把标记写在末尾 → 生成出来的 `产出/<团>_关系网.md` 下一轮就被
    #    当成"人工维护"、再也更新不了，每跑一次 visualize 就多一个「自动更新建议」文件。
    lines = [f"{AUTO_MARK} -->", f"# {group} · 关系网", ""]
    lines.append(f"- 生成: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"- 角色 {len(chars)} · 关系 {len(rels)}")
    lines.append("")
    lines.append("## 一、人物")
    lines.append("")
    lines.append("| 角色 | 身份 | 扮演 | 标签 | 简介 |")
    lines.append("|---|---|---|---|---|")
    for c in sorted(chars, key=lambda x: str(x.get("id", ""))):
        lines.append(
            f"| {c.get('name','')} | {str(c.get('identity',''))[:40]} | {c.get('played_by') or '-'} "
            f"| {'/'.join(c.get('tags') or [])} | {str(c.get('note') or '')[:70]} |"
        )
    lines += ["", "## 二、关系", ""]
    lines.append("| 人物A | 关系 | 强度 | 人物B | 事件依据 |")
    lines.append("|---|---|---|---|---|")
    for r in rels:
        a = by_id.get(r.get("from"), {}).get("name", r.get("from"))
        b = by_id.get(r.get("to"), {}).get("name", r.get("to"))
        lines.append(
            f"| {a} | {r.get('type','')} | {r.get('strength','')} | {b} | {str(r.get('event') or '')[:80]} |"
        )
    cross = [c for c in chars if "跨团" in (c.get("tags") or [])]
    lines += ["", f"## 三、跨团角色（{len(cross)}）", ""]
    for c in cross:
        lines.append(f"- **{c.get('name')}**：{c.get('note','')}")
    todo = [c for c in chars if "待确认" in (c.get("tags") or [])]
    lines += ["", f"## 四、待确认（{len(todo)}）", ""]
    for c in todo:
        lines.append(f"- {c.get('name')}：{c.get('note','')}")
    lines += ["", "---", "", f"{AUTO_MARK} ({datetime.now().strftime('%Y-%m-%d')}) -->"]
    return "\n".join(lines) + "\n"


def jack_dossier(ws: Workspace, cfg: Config) -> str:
    chars_doc = json.loads(ws.data_file("characters").read_text(encoding="utf-8"))
    chars = chars_doc.get("characters", [])
    jack = [c for c in chars if c.get("id") in cfg.visualize.jack_ids or "杰克" in (c.get("name") or "")]
    if not jack:
        return (f"{AUTO_MARK} -->\n# 杰克档案\n\n"
                f"（数据里没有找到杰克节点, 配置项 visualize.jack_ids = {cfg.visualize.jack_ids}）\n")
    # 首行标记（理由见 relations_md 的注释）；杰克档案是**手写正本**，只有它自己带首行标记
    # 才会被就地覆盖——现存那份没有标记，所以永远走「建议文件」分支（这是设计意图）。
    lines = [f"{AUTO_MARK} -->", "# 🎩 杰克 · 档案（由数据自动生成）", ""]
    lines.append(f"- 生成: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"- 节点: {', '.join(f'`{c.get('id')}`' for c in jack)}")
    lines.append("")
    for c in jack:
        lines.append(f"## {c.get('name')}")
        if c.get("identity"):
            lines.append(f"- **定位**：{c['identity']}")
        if c.get("note"):
            lines.append(f"- **概述**：{c['note']}")
        lines.append(f"- **出场团**：{'、'.join(c.get('groups') or [])}")
        lines.append("")
        lines.append("### 分团事件")
        for ev in c.get("events") or []:
            lines.append(f"**{ev.get('group')}**")
            for it in ev.get("items") or []:
                lines.append(f"- {it}")
            lines.append("")
    lines.append("---")
    lines.append(f"{AUTO_MARK} ({datetime.now().strftime('%Y-%m-%d')}) -->")
    return "\n".join(lines) + "\n"


def universe_overview(ws: Workspace) -> str:
    chars_doc = json.loads(ws.data_file("characters").read_text(encoding="utf-8"))
    rels_doc = json.loads(ws.data_file("relations").read_text(encoding="utf-8"))
    prof_doc = json.loads(ws.data_file("pl_profiles").read_text(encoding="utf-8"))
    chars = chars_doc.get("characters", [])
    rels = rels_doc.get("relations", [])
    groups: dict[str, dict[str, int]] = {}
    for c in chars:
        for g in (char_groups(c) or ["(未标注)"]):
            groups.setdefault(g, {"chars": 0, "cross": 0})
            groups[g]["chars"] += 1
            if "跨团" in (c.get("tags") or []):
                groups[g]["cross"] += 1
    # 首行标记（理由见 relations_md 的注释）
    lines = [f"{AUTO_MARK} -->", "# 跑团宇宙总览（由数据自动生成）", ""]
    lines.append(f"- 生成: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"- 合计：**{len(chars)} 角色 / {len(rels)} 关系 / "
                 f"{len(prof_doc.get('profiles') or [])} 位 PL / {len(groups)} 个团**")
    lines.append("")
    lines.append("| 团 | 角色数 | 其中跨团 |")
    lines.append("|---|---|---|")
    for g, st in sorted(groups.items(), key=lambda kv: -kv[1]["chars"]):
        lines.append(f"| {g} | {st['chars']} | {st['cross']} |")
    cross_all = [c for c in chars if "跨团" in (c.get("tags") or [])]
    lines += ["", f"## 跨团角色（{len(cross_all)}）", ""]
    for c in cross_all:
        lines.append(f"- **{c.get('name')}**（`{c.get('id')}`）：{(c.get('note') or '')[:100]}")
    todo = [c for c in chars if "待确认" in (c.get("tags") or [])]
    lines += ["", f"## 待确认角色（{len(todo)}）", ""]
    for c in todo:
        lines.append(f"- {c.get('name')}：{(c.get('note') or '')[:100]}")
    lines += ["", "---", f"{AUTO_MARK} ({datetime.now().strftime('%Y-%m-%d')}) -->"]
    return "\n".join(lines) + "\n"


def run_visualize(ws: Workspace, cfg: Config, group: str | None = None, all_groups: bool = False) -> dict[str, Any]:
    ws.ensure_dirs()
    result: dict[str, Any] = {"net": [], "pl_wall": None, "docs": []}

    if cfg.visualize.net_enabled:
        groups = [group] if group else manifest_groups(ws) if all_groups else []
        if group is None and not all_groups:
            log.info("未指定 --group, 只生成宇宙级产物(PL墙/总览/杰克档案)")
        for g in groups:
            try:
                r = net_html.build(ws, g)
                r["group"] = g
                result["net"].append(r)
            except (FileNotFoundError, json.JSONDecodeError) as e:
                log.warn(f"[{g}] 关系图生成跳过: {e}")

    if cfg.visualize.pl_wall:
        try:
            result["pl_wall"] = pl_html.build(ws)
        except (FileNotFoundError, json.JSONDecodeError) as e:
            log.warn(f"PL 画像墙跳过: {e}")

    if cfg.visualize.jack_dossier:
        result["docs"].append(_write_doc(ws.output / "杰克档案.md", jack_dossier(ws, cfg), "杰克档案", ws))
    result["docs"].append(
        _write_doc(ws.output / "跑团宇宙总览.md", universe_overview(ws), "宇宙总览", ws)
    )
    if group:
        result["docs"].append(
            _write_doc(ws.output / f"{group}_关系网.md", relations_md(ws, group), f"{group} 关系网", ws)
        )
    return result


def manifest_groups(ws: Workspace) -> list[str]:
    """优先用 manifest 的团列表; 没有 manifest 时退化为"数据里出现过的团"。"""
    from trpg_agent.ingest import load_manifest

    m = load_manifest(ws)
    if m:
        return [g for g in m["groups"] if g not in set(m.get("superseded_groups") or [])]
    try:
        chars = json.loads(ws.data_file("characters").read_text(encoding="utf-8")).get("characters", [])
    except (FileNotFoundError, json.JSONDecodeError):
        return []
    return collect_groups(chars)
