# -*- coding: utf-8 -*-
"""给「本来就是自动生成物」的产出文档补上**首行** AUTO-GENERATED 标记，让 visualize 能就地维护。

背景（2026-10-05 发现的真 bug）：`relations_md()` / `universe_overview()` 把标记写在**文件末尾**，
而 `_write_doc()` 只看**开头 200 字**判断"是不是自动生成物" →
生成的 `<团>_关系网.md` 下一轮就被当成"人工维护"，**永远更新不了**，
每跑一次 visualize 就多一个 `.trpg/reports/<文件>_自动更新建议.md`。
生成端已修（首行标记）；本工具把**已存在的**那些派生文档补上首行标记。

⚠️ **不碰** `产出\杰克档案.md` —— 那是手写正本，按设计就该走"建议文件"分支。

用法:
    python tools/_adopt_auto_marker.py            # dry-run
    python tools/_adopt_auto_marker.py --apply
"""
from __future__ import annotations

import os
import shutil
import sys
from datetime import datetime
from pathlib import Path

WS = Path(os.environ.get("TRPG_WS", "workspace"))     # TRPG关系网
OUT = WS / "\u4ea7\u51fa"                              # 产出
REPORTS = WS / ".trpg" / "reports"
MARK = "<!-- AUTO-GENERATED by trpg-agent"

# 明确是派生文档的：所有 <团>_关系网.md + 跑团宇宙总览.md（交接文档里已写明它是自动生成物）
NEVER = {"杰克档案.md"}


def targets() -> list[Path]:
    out = sorted(OUT.glob("*_\u5173\u7cfb\u7f51.md"))          # *_关系网.md
    ov = OUT / "\u8dd1\u56e2\u5b87\u5b99\u603b\u89c8.md"        # 跑团宇宙总览.md
    if ov.is_file():
        out.append(ov)
    return [p for p in out if p.name not in NEVER]


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError, ValueError):
        pass
    apply = "--apply" in sys.argv
    todo, skip = [], []
    for p in targets():
        head = p.read_text(encoding="utf-8", errors="replace")[:200]
        (skip if MARK in head else todo).append(p)

    print(f"待补首行标记 {len(todo)} 个：")
    for p in todo:
        print(f"  {p.name}")
    if skip:
        print(f"已是首行标记、跳过 {len(skip)} 个：")
        for p in skip:
            print(f"  {p.name}")
    if not apply:
        print("\n(dry-run; 加 --apply 写入)")
        return 0

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    bdir = REPORTS / f"_adopt_bak_{stamp}"
    bdir.mkdir(parents=True, exist_ok=True)
    for p in todo:
        shutil.copy2(p, bdir / p.name)
        body = p.read_text(encoding="utf-8")
        p.write_text(f"{MARK} -->\n{body}", encoding="utf-8")
        print(f"  + {p.name}")
    print(f"\n已补 {len(todo)} 个（原件备份在 {bdir}）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
