# -*- coding: utf-8 -*-
"""采用自动生成的《跑团宇宙总览》正本，并把两份人工文档同步进 KB 包。

背景：
  * `产出\\跑团宇宙总览.md` 其实**是自动生成物**，只是末尾的标记带了日期
    (`<!-- AUTO-GENERATED by trpg-agent (2026-10-03) -->`)，工具按精确串匹配 -> 没认出来，
    于是只写了 `.trpg\\reports\\跑团宇宙总览_自动更新建议.md`。采用新版（顶部带精确标记）后，
    以后 visualize 会直接维护它。
  * `产出\\杰克档案.md` 是**手写正本**（含维护规则：「每团出现杰克相关事件必须实时更新本档案
    并同步 KB 包 `astrbot知识库导入\\00c_杰克档案.md`」）-> 本脚本负责那次同步。

用法: python tools/_sync_manual_docs.py [--apply]
"""
from __future__ import annotations

import os
import shutil
import sys
from datetime import datetime
from pathlib import Path

WS = Path(os.environ.get("TRPG_WS", "workspace"))
OUT = WS / "\u4ea7\u51fa"
REPORTS = WS / ".trpg" / "reports"
KB = OUT / "astrbot\u77e5\u8bc6\u5e93\u5bfc\u5165"

PAIRS = [
    # (源, 目标, 说明)
    (REPORTS / "\u8dd1\u56e2\u5b87\u5b99\u603b\u89c8_\u81ea\u52a8\u66f4\u65b0\u5efa\u8bae.md",
     OUT / "\u8dd1\u56e2\u5b87\u5b99\u603b\u89c8.md", "总览采用自动版（含精确 AUTO 标记）"),
    (OUT / "\u8dd1\u56e2\u5b87\u5b99\u603b\u89c8.md",
     KB / "00_\u8dd1\u56e2\u5b87\u5b99\u603b\u89c8.md", "同步 KB 包"),
    (OUT / "\u6770\u514b\u6863\u6848.md",
     KB / "00c_\u6770\u514b\u6863\u6848.md", "同步 KB 包（维护规则要求）"),
]


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError, ValueError):
        pass
    apply = "--apply" in sys.argv
    ts = f"{datetime.now():%Y%m%d_%H%M%S}"
    for src, dst, desc in PAIRS:
        if not src.is_file():
            print(f"!! 源不存在 {src}")
            continue
        n_src = len(src.read_bytes())
        n_dst = len(dst.read_bytes()) if dst.is_file() else -1
        print(f"{desc}\n  {src.name} ({n_src} B) -> {dst.name} (旧 {n_dst} B)")
        if not apply:
            continue
        if dst.is_file():
            shutil.copy2(dst, dst.with_name(dst.name + f".bak_docsync_{ts}"))
        shutil.copy2(src, dst)
    if not apply:
        print("\n(dry-run; 加 --apply 写入)")
        return 0
    print("\n已写入（各自留 .bak_docsync_* 备份）")
    for _s, dst, _d in PAIRS:
        print(f"  {dst.name}: {dst.stat().st_size} B")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
