# -*- coding: utf-8 -*-
"""收尾(housekeep): 汇总各步状态 / 数据量 / 待确认 -> 产出收尾清单。

不做任何破坏性动作; README/交接文档这类人工资产只出「建议」不覆盖。
"""
from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from trpg_agent import log
from trpg_agent.config import Config
from trpg_agent.data_utils import char_groups
from trpg_agent.state import all_states
from trpg_agent.workspace import Workspace

AUTO_MARK = "<!-- AUTO-GENERATED by trpg-agent"


def _load(path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, FileNotFoundError):
        return None


def run_housekeep(ws: Workspace, cfg: Config) -> dict[str, Any]:
    ws.ensure_dirs()
    counts: dict[str, int] = {}
    for kind, key in (("characters", "characters"), ("relations", "relations"),
                      ("players", "players"), ("pl_profiles", "profiles")):
        doc = _load(ws.data_file(kind))
        counts[kind] = len(doc.get(key, [])) if isinstance(doc, dict) else 0

    chars = (_load(ws.data_file("characters")) or {}).get("characters", [])
    groups: dict[str, int] = {}
    for c in chars:
        for g in char_groups(c):
            groups[g] = groups.get(g, 0) + 1
    todo = [c for c in chars if "待确认" in (c.get("tags") or [])]

    lines = ["# 收尾清单（由 trpg-agent 自动生成）", ""]
    lines.append(f"- 生成: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"- 工作区: `{ws.root}`")
    lines.append("")
    lines.append("## 一、数据量")
    lines.append("")
    lines.append("| 种类 | 条数 |")
    lines.append("|---|---|")
    for k, v in counts.items():
        lines.append(f"| {k} | {v} |")
    lines.append("")
    lines.append(f"## 二、团分布（{len(groups)} 团）")
    lines.append("")
    lines.append("| 团 | 角色数 |")
    lines.append("|---|---|")
    for g, n in sorted(groups.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {g} | {n} |")
    lines.append("")
    lines.append("## 三、流程状态")
    lines.append("")
    lines.append("| 步骤 | 状态 | 说明 |")
    lines.append("|---|---|---|")
    for name, st in all_states(ws).items():
        lines.append(f"| {name} | {st.status} | {st.data.get('message', '')} |")
    lines.append("")
    lines.append(f"## 四、待确认角色（{len(todo)}）")
    lines.append("")
    for c in todo:
        lines.append(f"- {c.get('name')}：{(c.get('note') or '')[:120]}")
    if not todo:
        lines.append("_(无)_")
    lines.append("")
    pend_dir = ws.reports
    if pend_dir.is_dir():
        pends = sorted(pend_dir.glob("*_待确认.md"))
        if pends:
            lines.append(f"## 五、入库待确认清单（{len(pends)} 份）")
            lines.append("")
            for p in pends:
                lines.append(f"- `{ws.rel(p)}`")
            lines.append("")
    unclassified = (_load(ws.work / "manifest.json") or {})
    if unclassified.get("superseded_groups"):
        lines.append("## 六、已停用的来源团")
        lines.append("")
        for g in unclassified["superseded_groups"]:
            lines.append(f"- {g}（其导出已按日期拆分为多团）")
        lines.append("")
    lines.append("---")
    lines.append(f"{AUTO_MARK} ({datetime.now().strftime('%Y-%m-%d')}) -->")

    out = ws.output / "收尾清单.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.ok(f"收尾清单: {ws.rel(out)}")
    log.info(f"数据量: " + " / ".join(f"{k}={v}" for k, v in counts.items()) + f" · 待确认角色 {len(todo)}")
    return {"path": ws.rel(out), "counts": counts, "groups": len(groups), "todo": len(todo)}
